[build]
  publish = "."

[build.processing]
  skip = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = false
  minify = true

[build.processing.html]
  pretty_urls = true
